<?php

namespace App\Http\Controllers;

use App\Entities\Client;
use App\Entities\DniType;
use Illuminate\Http\Request;
use App\Http\Repositories\ClientsRepo as Repo;
use Illuminate\Routing\Route;
use Illuminate\Support\Carbon;

class ClientsController extends Controller
{

    protected $repo;
    protected $module;
    protected $route;

    public function __construct(Repo $repo, Route $route)
    {
        $this->repo = $repo;
        $this->route = $route;
        $confFile = 'clients';

        // nombre de archivo de configuracion

        $this->confFile = $confFile;
        $this->data['confFile'] = $confFile;

    }



    public function create()
    {
        $this->data['provinces'] = ["Capital Federal", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago Del Estero", "Tierra Del Fuego", "Tucuman"];
        $this->data['dniTypes'] = DniType::all()->pluck('type', 'id');

        return parent::create(); // TODO: Change the autogenerated stub
    }

    public function update(Request $request)
    {
        $validaciones = config('clients.validationsStore');
        $validaciones['dni'] = "numeric|unique:clients,dni,".$this->route->parameter('id');
        $validaciones['cuil'] =

        $request->validate($validaciones,config($this->confFile.'.messagesUpdate'));

        $model = $this->repo->find($this->route->id);

        $model->fill($request->all());

        $model->save();

        return redirect()->route(config($this->confFile.".viewIndex"))->with('ok','Registro Editado.');

    }

    public function edit()
    {
        $this->data['provinces'] = ["Capital Federal", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago Del Estero", "Tierra Del Fuego", "Tucuman"];
        $this->data['dniTypes'] = DniType::all()->pluck('type', 'id');

        return parent::edit(); // TODO: Change the autogenerated stub
    }

    public function financing()
    {
        $this->data['client'] = Client::with('Loans')->find($this->route->parameter('id'));

        if(! $this->data['client'])
            return redirect()->back()->withError('El cliente no existe');

        $this->data['history'] = $this->data['client']->Loans->groupBy(function($date){
            return Carbon::parse($date->created_at)->format('Y');
        });

        return view('clients.history')->with($this->data);
    }
}
